### ISSUE TITLE
Installing Issues

### ISSUE THREAD

**Issue by ggmirandac** [anthbapt/triaction#1]
Hi,

I am trying to install Triaction software and I have encountered some error in the installation procedure. 

when I am trying to install the software using the command that is in the Readme I have the following issue:

```shell
Traceback (most recent call last):
  File "../GitHub-Downloads/triaction/setup.py", line 81, in <module>
    version=get_version("triaction/__init__.py"),
  File "../GitHub-Downloads/triaction/setup.py", line 27, in get_version
    for line in read(rel_path).splitlines():
  File "../GitHub-Downloads/triaction/setup.py", line 23, in read
    with codecs.open(os.path.join(here, rel_path), 'r') as fp:
  File "/../lib/python3.10/codecs.py", line 906, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '../GitHub-Downloads/triaction/triaction/__init__.py'
```
Just so you know I eliminated some of the files for privacy. The important issue is that it seems like the `__init__.py` file is missing for the instalation.

Bests,

**Comment by anthbapt** [comment]
Hello,

Thank you for using Triaction. I added the __init__.py file and checked the installation. It should work now. There is only a warning message due to a package coniii, which uses an old version of numba. Can you please confirm that it works on your computer too? If you have any other questions, please feel free to ask or contact me at my email address: abaptista@turing.ac.uk.

Best wishes,
Anthony

**Comment by anthbapt** [comment]
Solved, removed old dependency to coniii and pyitlib
